export const menuItemsData = [
  {
    id: 1,
    name: "Triple Cheese American Veg Burger",
    info: "A crunchy Corn patty filled with Cheese, topped with Jalapenos, shredded Lettuce and more cheese, layered between the goodness of whole wheat buns.",
    price: 195,
    image: "burger/burger1.png",
  },
  {
    id: 2,
    name: "McSpicy Premium Veg Burger",
    info: "A spicy Paneer patty, shredded Lettuce topped with Jalapenos and Cheese slice, Spicy Cocktail sauce & Cheese sauce layered between toasted Whole Wheat Buns.",
    price: 210,
    image: "burger/burger2.png",
  },
  {
    id: 3,
    name: "McAloo Tikki Burger",
    info: "The World's favourite Indian burger! Crunchy potato and peas patty with delicious Tom Mayo & crunchy onions; now with Whole Wheat Bun",
    price: 49,
    image: "burger/burger3.png",
  },
  {
    id: 4,
    name: "McVeggie Burger",
    info: "An everyday classic burger with a delectable patty filled with potatoes, carrots and tasty Indian spices; topped with crunchy lettuce and mayonaise.",
    price: 115,
    image: "burger/burger4.png",
  },
  {
    id: 5,
    name: "McSpicy Paneer Burger",
    info: "Rich and filling cottage cheese patty coated in spicy, crispy batter topped with a creamy sauce and crispy shredded lettuce will have you craving for more.",
    price: 165,
    image: "burger/burger5.png",
  },
  {
    id: 6,
    name: "Masala McEgg Burger",
    info: "Get your protein fix with the Masala McEgg Burger- steamed egg patty, topped with spicy masala seasoning, onions and habanero sauce",
    price: 50,
    image: "burger/burger6.png",
  },
  {
    id: 7,
    name: "Mexican McAloo Tikki Burger",
    info: "A burger with a fusion of international tastes- your favourite aloo tikki patty, layered with shredded onion, jalapeno, served with delicious Chipotle sauce",
    price: 55,
    image: "burger/burger7.png",
  },
  {
    id: 8,
    name: "McSpicy Chicken Burger",
    info: "Tender and juicy chicken patty coated in spicy, crispy batter topped with a creamy sauce and crispy shredded lettuce will have you craving for more.",
    price: 165,
    image: "burger/burger8.png",
  },
  {
    id: 9,
    name: "McChicken Burger",
    info: "Tender and juicy chicken patty cooked to perfection, with creamy mayonnaise and crunchy lettuce adding flavour to each bite.",
    price: 120,
    image: "burger/burger9.png",
  },
  {
    id: 10,
    name: "Cheese Lava American Veg Burger",
    info: "A sinfully oozing cheesy Veg patty, loaded with Roasted Chipotle sauce, shredded Onions, Jalapenos & a relishing salad, layered between freshly toasted Buns.",
    price: 230,
    image: "burger/burger10.png",
  },
  {
    id: 11,
    name: "Double Cheese Margherita",
    info: "A classic delight loaded with extra 100% real mozzarella cheese",
    price: 379,
    image: "pizza/pizza1.png",
  },
  {
    id: 12,
    name: "Peppy Paneer",
    info: "Flavorful trio of juicy paneer, crisp capsicum with spicy red paprika",
    price: 459,
    image: "pizza/pizza2.png",
  },
  {
    id: 13,
    name: "Margherita",
    info: "Classic delight with 100% real mozzarella cheese",
    price: 239,
    image: "pizza/pizza3.png",
  },
  {
    id: 14,
    name: "Farmhouse",
    info: "Delightful combination of onion, capsicum, tomato & grilled mushroom",
    price: 459,
    image: "pizza/pizza4.png",
  },
  {
    id: 15,
    name: "Mexican Green Wave",
    info: "Mexican herbs sprinkled on onion, capsicum, tomato & jalapeno",
    price: 459,
    image: "pizza/pizza5.png",
  },
  {
    id: 16,
    name: "Deluxe Veggie",
    info: "Veg delight - onion, capsicum, grilled mushroom, corn & paneer",
    price: 549,
    image: "pizza/pizza6.png",
  },
  {
    id: 17,
    name: "Cheese n Corn",
    info: "A delectable combination of sweet & juicy golden corn",
    price: 379,
    image: "pizza/pizza7.png",
  },
  {
    id: 18,
    name: "Paneer Makhani",
    info: "Flavorful twist of spicy makhani sauce topped with paneer & capsicum",
    price: 549,
    image: "pizza/pizza8.png",
  },
  {
    id: 19,
    name: "Pepper Barbecue Chicken",
    info: "Pepper barbecue chicken for that extra zing",
    price: 449,
    image: "pizza/pizza9.png",
  },
  {
    id: 20,
    name: "Chicken Fiesta",
    info: "Grilled chicken rashers, peri-peri chicken, onion & capsicum, a complete fiesta",
    price: 559,
    image: "pizza/pizza10.png",
  },
];
